### ISSUE TITLE
Program Hangs When a Thread is not an image

### ISSUE THREAD

**Issue by dionytadema** [Rawns/Reddit-Wallpaper-Changer#10]
RCW hangs on setting a background if the thread it selected is not an image thread, this is an issue because the reddit i want to use also contains other forms of media such as albums and videos ([r/eveporn](https://www.reddit.com/r/eveporn))

included log
[RWC.txt](https://github.com/Rawns/Reddit-Wallpaper-Changer/files/639345/RWC.txt)

**Comment by dionytadema** [comment]
i looked into the code, an easy fix would be to do a check to see if the URL ends in a supported image format in the setwallpaper fucntion

**Comment by Rawns** [comment]
Thanks for the info. I'll get this ironed out for the next release. :)

**Comment by Rawns** [comment]
Added a check to ensure URL is for an image in 1.0.8.5
