### ISSUE TITLE
Windows 10 Subreddit probably doesnt exist

### ISSUE THREAD

**Issue by lDarkPhoton** [Rawns/Reddit-Wallpaper-Changer#12]
so this program is up to date on 1.8.3 and like I still get this error. I love your app but it only changes the wallpaper when I start my computer. Its a real bummer cause I love my wallpaper to change every 10 minutes. It says that the subreddit doesnt exist for all the favorite subreddits whether its on random or hot or anything. I am on charter communications as a service provider. I also have ran spybot antibeacon and spybot immunizer but it shouldnt stop me from grabbing wallpapers cause it does it right as I login. What can I do to fix this issue? 

![reddit wallpaper blocker](https://cloud.githubusercontent.com/assets/25428317/22416323/ad764d88-e682-11e6-9e97-8942e68a6328.PNG)

**Comment by Rawns** [comment]
Hay, could you post the full lost of subs in your subreddit filed please? Also if you could copy the log file and stick it somewhere liek pastebin so I can take a look, it would be appreciated. :)

**Comment by Rawns** [comment]
Do'h! Wrong button!

**Comment by lDarkPhoton** [comment]
wallpapers+wallpaper+earthporn+spaceporn+skyporn+technologyporn+imaginarystarscapes

**Comment by lDarkPhoton** [comment]
it seems to be changing now after 1.8.4 update so I will email you back if
I keep having issues. You guys rock :D love my wallpaper changer and have
loved it for a long time now since 1.6

**Comment by Rawns** [comment]
Awesome! Glad it's working again. 👍

**Comment by Spunkie** [comment]
I'm still getting this issue on 1.0.12.0. I believe it's related to reddit search being down/overloaded since every time this shows up in the log its immediately preceded by another error that says `Reddit Server Unavailable`.

```
3/8/2017 11:29:22 AM - WIN-3ANMC1H9IUV: Changing wallpaper.
3/8/2017 11:29:22 AM - WIN-3ANMC1H9IUV: The background worker started successfully and is looking for a wallpaper.
3/8/2017 11:29:22 AM - WIN-3ANMC1H9IUV: Sellected sub to search: wallpapers
3/8/2017 11:29:22 AM - WIN-3ANMC1H9IUV: Full URL Search String: http://www.reddit.com/r/wallpapers/search.json?q=2560x1440+OR+1440p+OR+WQHD+NOT+(title%3a+car+OR+title%3a+lamborghini+OR+BMW)+self%3Ano+((url%3A.png+OR+url%3A.jpg+OR+url%3A.jpeg)+OR+(url%3Aimgur.png+OR+url%3Aimgur.jpg+OR+url%3Aimgur.jpeg)+OR+(url%3Adeviantart))&sort=top&restrict_sr=on&t=all
3/8/2017 11:29:22 AM - WIN-3ANMC1H9IUV: Searching Reddit for a wallpaper.
3/8/2017 11:29:35 AM - WIN-3ANMC1H9IUV: Reddit Server Unavailable, try again later.
3/8/2017 11:29:35 AM - WIN-3ANMC1H9IUV: Subreddit probably does not exist.
```
