### ISSUE TITLE
[BUG] Interval value overload

### ISSUE THREAD

**Issue by meehanman** [Rawns/Reddit-Wallpaper-Changer#31]
Setting the interval to [60] [Days] and pressing [Save] causes the value of Interval to overload displaying an Unhandled exception with the error message:

Value '-2147483648' is not a valid value for Interval. Interval must be greater than 0. Parameter name. Interval. 

--
I suggest using BigInteger instead of Integer to store the value of Interval as well as surrounding the setting  of Interval in a try catch block.

**Comment by Rawns** [comment]
Thanks for the report. I'll get it fixed in the next release. :)

**Comment by Rawns** [comment]
Addressed. Went with the easier option of adding checks so that now, 7 days is the upper limit. 

To be honest I can't imagine anyone wanting to change their wallpaper less than daily anyway so I think a 7 day upper limit is more then enough. :)

**Comment by Rawns** [comment]
Will close once live.

**Comment by Rawns** [comment]
Live.
