### ISSUE TITLE
MessageBox "No Results After 50 Retries. Disabling Reddit Wallpaper Changer."

### ISSUE THREAD

**Issue by lapoigne** [Rawns/Reddit-Wallpaper-Changer#35]
On my office, sometimes the internet gone for long time the night, waiting for the router to reboot :(
On the morning, when I come back, I see lots of messagebox on my desktop (more than 50).
I propose to replace the message with a BalloonTipIcon to avoid that.

Replace on RWC.cs line 640:
```MessageBox.Show("No Results After 50 Retries. Disabling Reddit Wallpaper Changer.", "Reddit Wallpaper Changer: Error", MessageBoxButtons.OK, MessageBoxIcon.Error);```
with
```taskIcon.BalloonTipIcon = ToolTipIcon.Error;
taskIcon.BalloonTipTitle = "Reddit Wallpaper Changer";
taskIcon.BalloonTipText = "No Results After 50 Retries. Disabling Reddit Wallpaper Changer.";
taskIcon.ShowBalloonTip(700);```

**Comment by Rawns** [comment]
Thanks for the suggestion. I'll review the code and see about changing it. :)

**Comment by Rawns** [comment]
Changed form message box to notification. Will close once live in the next release.

**Comment by Rawns** [comment]
Live.
