### ISSUE TITLE
Spelling error in the log file....

### ISSUE THREAD

**Issue by Rawns** [Rawns/Reddit-Wallpaper-Changer#37]
The worst kind!!!

`26/02/2017 17:19:20 - PAUL-DESKTOP: Reddit Wallpaper Changer is shitting down.`

**Comment by Rawns** [comment]
Fix pushed to dev branch. Will close once live!

**Comment by Spunkie** [comment]
This fix is clearly a regression, totally unusable now. 



 :trollface:

**Comment by Rawns** [comment]
Fixed in 1.0.13.
