### ISSUE TITLE
Fallback to saved wallpapers when a new one can't be found.

### ISSUE THREAD

**Issue by Spunkie** [Rawns/Reddit-Wallpaper-Changer#43]
I'm running a 1440p monitor so search seems to sometimes(often) have trouble finding me a new wallpaper within the 50 retries limit. 

It would be nice if instead of displaying an error and not changing the wallpaper it would instead fallback to using one of the ones I already have downloaded. At least until the next time it's supposed to search that is.

----

Also I'm not really sure if search is supposed to fail this often so here is my query if you are interested.
```
subreddits -- MinimalWallpaper+wallpapers+wallpaper+NSFW_Wallpapers+Artsy_NSFW_Wallpapers+WQHD_Wallpaper+ghibli+bigwallpapers+MachinePorn+GeekPorn+spaceporn+EarthPorn+Offensive_Wallpapers
query -- 2560x1440 OR 1440p OR WQHD NOT (title: car OR title: lamborghini OR title: BMW)
```

**Comment by Rawns** [comment]
Interesting idea. I can certainly look at implementing something like that for when RWC can't find new wallpapers after 50 trys (or you go offline). I guess there might be a few factors to consider though as I'm sure that not everyone saves/auto saves wallpapers so it might need something included to auto save some anyway.  I'll add it to the list of suggestions. 

I might also look at just removing the 50 retries all together and let it retry infintely.

**Comment by Rawns** [comment]
Added to the ideas list in the project plan.
