### ISSUE TITLE
Screen Flash

### ISSUE THREAD

**Issue by mlubbs** [Rawns/Reddit-Wallpaper-Changer#45]
Every time the wallpaper changes the screen flashes and it seems as if the focus is momentarily taken off of what I am doing.

**Comment by Rawns** [comment]
Do you have the 'Wallpaper info popup' enabled in the settings? if so, would you mind disabeling it to see if that helps?

**Comment by mlubbs** [comment]
The only option enabled are:
Auto Start
Start in Tray
Suppress Duplicates
Wallpaper Fade Effect

**Comment by Rawns** [comment]
Hopefully fixed in 1.0.13.
