### ISSUE TITLE
It keeps saying "Nothing found after 50 attempts, Shutting down"

### ISSUE THREAD

**Issue by Bewinxed** [Rawns/Reddit-Wallpaper-Changer#46]
Title.

log file here:

http://pastebin.com/Hua4ER3i

Tried multiple options for wallpapers selection "top week/day/month"

I'm only pulling from /r/wallpapers, and i have windows 10

Yet the app still works but still throws the notification.

**Comment by Rawns** [comment]
Looking at the log file, it looks like most wallpapers it's pulled have already been used.

At the moment, RWC treats that as a failed attempt to grab a new paper. Closing/reopening to clear the history will sort it, or disable the 'Suppress duoplicates' option. Long term I think I'll just do away with the 50 retrys cap.
