### ISSUE TITLE
Configurations not deleted on uninstall

### ISSUE THREAD

**Issue by EmmanuelMess** [Rawns/Reddit-Wallpaper-Changer#49]
Configurations not deleted on uninstall on W10.

**Comment by Rawns** [comment]
Thanks for the info. This is expected behaviour from the MSI install, and as the files are only a few KB in size, I don't think it's really too much of an issue.

**Comment by EmmanuelMess** [comment]
But I uninstalled and installed hoping to have the original config, and it reloaded the last config. There should at least be a way to know where it is (wasn't in the folder where RWC was installed).
