### ISSUE TITLE
Unable to install - Source file not found (Reddit Wallpaper Changer.exe) 

### ISSUE THREAD

**Issue by Baetek** [Rawns/Reddit-Wallpaper-Changer#5]
```
System Info:
Windows 10 Pro 14393.222 (Standard Stable)
Same issue across 2 different computers (AMD desktop and Surface Pro 3)
```

Getting `Source file not found: ...Reddit Wallpaper Changer.exe. Verify that the file exists and that you can access it.` when trying to install (once the installer starts and progress bar starts going)

Logged in an admin account on both computers.

Tried installing into 
 - C:\
 - Program Files
 - User Documents Folder
 - External Drive

Tried changing between 'Just for Me' & 'Everyone' installation options.

Finally tried launching the installer as admin through the command prompt with msiexec /a installer-path.

Same error everytime

UPDATE & TEMP WORKAROUND:

Manually downloading the file `Reddit Wallpaper Changer.exe` from `Rawns/Reddit-Wallpaper-Changer/Reddit Wallpaper Changer Installer/Debug/` and placing it in the same directory as the MSI installer fixes the problem.

**Comment by Rawns** [comment]
Additional Work Around: Download the self extracting zip file from the releases area. 

https://github.com/Rawns/Reddit-Wallpaper-Changer/releases/download/release/Reddit.Wallpaper.Changer.Setup.exe

**Comment by Baetek** [comment]
[Here is the .msi install log](http://pastebin.com/icnesjAD)

Got it with `msiexec /i "Reddit.Wallpaper.Changer.Setup.msi" /l*v "log.log"`

**Comment by Rawns** [comment]
Resolved. Seems the installer project was not happy having spaces in the name, causing the application exe file to not get bundled correctly in the installer. A new MSI will be made available with the next release.
