### ISSUE TITLE
Rebuild thumbnails crashes when there are no images saved

### ISSUE THREAD

**Issue by EmmanuelMess** [Rawns/Reddit-Wallpaper-Changer#50]
I am having basically random crashes when clicking "Rebuild thumbnails" on windows 10 when there are no images saved.
[Reddit Wallpaper Changer.exe.config.txt](https://github.com/Rawns/Reddit-Wallpaper-Changer/files/903255/Reddit.Wallpaper.Changer.exe.config.txt)

**Comment by Rawns** [comment]
Replicated. I'll get this fixed in the next release.

**Comment by Rawns** [comment]
Fix comitted to dev branch. Will be live in 1.0.14.0
