### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by healyr22** [Rawns/Reddit-Wallpaper-Changer#55]
Getting a 503 error every time I try to update the wallpaper now

**Comment by healyr22** [comment]
https://pastebin.com/HwNFCf24

**Comment by Rawns** [comment]
Alas, I can't replicate this, or see form the logs why it's happening. The 503 response comes from Reddit's side when a search query is submitted, and as no one else seems to be continusly getting this, I can't really fix it I'm afriad.
