### ISSUE TITLE
RWC Won't Load New Wallpapers

### ISSUE THREAD

**Issue by xpboy7** [Rawns/Reddit-Wallpaper-Changer#57]
Yo man!
I'm using RWC for far too long, only last week I found out there was an 'updated' version.
Since I've updated the software I can't get it to change wallpapers.
See attached log - https://pastebin.com/BJNstAf5
Thanks a whole lot for helping the community.

Cheers,

**Comment by Rawns** [comment]
Hay chap.  Disable the "Validate wallpaper sizes" option. This option forces RWC to **only** apply wallpapers that match your exact screen resolution (3360x1158). Disabeling this and saving will get it working again. :)

**Comment by xpboy7** [comment]
Thanks dude it works great!
