### ISSUE TITLE
Suggestion - change only when computer in use

### ISSUE THREAD

**Issue by mariov96** [Rawns/Reddit-Wallpaper-Changer#70]
Hi,
I've got a suggestion that would improve the app IMO.
Simply when I'm not actively looking at the desktop or using the computer changing the background is unnecessary network traffic and compute energy.
On top of that I wouldnt even see the image!
Suggest a flag to only change desktop when the computer is in use.
Also like to see a notification showing the new picture briefly - this way even if my desktop is hidden I'm given a visual que that something cool has happened.
Thank you for the app and keep up the great work!
Best,
Mario

**Comment by Rawns** [comment]
Thanks for the feedback, I'll add it to the list of  potential enhancements. :)
