### ISSUE TITLE
Right click, change wallpaper, log says changing, but no change

### ISSUE THREAD

**Issue by gmarcom** [Rawns/Reddit-Wallpaper-Changer#9]
[RWC.txt](https://github.com/Rawns/Reddit-Wallpaper-Changer/files/542118/RWC.txt)

I have uploaded the log file. It shows that it finds a new wallpaper but it is not changing it.

For what it's worth, this program is awesome!! Love the idea of coming in each morning and having a new wallpaper.
The older program worked. This is the first time I tried the fork.

**Comment by Rawns** [comment]
Thanks, I've noticed this too. It seems to be on first load. As a work around, just close the app, wait a couple of seconds and re-launch. This seems to "kick it" into action. I'll try and work out what's happening, and then get it fixed in a future release.

**Comment by Rawns** [comment]
Hay, I've pushed a new version (1.0.8.3) which hopefulyl addresses this. let me knwo if you have any joy or not.

**Comment by gmarcom** [comment]
Working GREAT!!
Thanks!!

**Comment by Rawns** [comment]
Awesome, thanks for the update. :)
